/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialesAmigurumisRouteImport } from './routes/tutoriales-amigurumis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialesAmigurumisRoute = TutorialesAmigurumisRouteImport.update({
  id: '/tutoriales-amigurumis',
  path: '/tutoriales-amigurumis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tutoriales-amigurumis': typeof TutorialesAmigurumisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tutoriales-amigurumis': typeof TutorialesAmigurumisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tutoriales-amigurumis': typeof TutorialesAmigurumisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tutoriales-amigurumis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tutoriales-amigurumis'
  id: '__root__' | '/' | '/tutoriales-amigurumis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TutorialesAmigurumisRoute: typeof TutorialesAmigurumisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutoriales-amigurumis': {
      id: '/tutoriales-amigurumis'
      path: '/tutoriales-amigurumis'
      fullPath: '/tutoriales-amigurumis'
      preLoaderRoute: typeof TutorialesAmigurumisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TutorialesAmigurumisRoute: TutorialesAmigurumisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
